### ISSUE TITLE
Failed to find any matching files for ./albert_large_zh/bert_model.ckpt

### ISSUE THREAD

**Issue by thousfeet** [brightmart/albert_zh#22]
在尝试用albert_large_zh模型跑fine-tuning时出错，按照以下命令执行
```
 export BERT_BASE_DIR=./albert_large_zh
    export TEXT_DIR=./lcqmc
    nohup python3 run_classifier.py   --task_name=lcqmc_pair   --do_train=true   --do_eval=true   --data_dir=$TEXT_DIR   --vocab_file=./albert_config/vocab.txt  \
    --bert_config_file=./albert_config/albert_config_large.json --max_seq_length=128 --train_batch_size=64   --learning_rate=2e-5  --num_train_epochs=3 \
    --output_dir=albert_large_lcqmc_checkpoints --init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt &
```
得到ERROR信息如下
```
ERROR:tensorflow:Error recorded from training_loop: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./albert_large_zh/bert_model.ckpt
E1013 17:11:41.890616 140328154277632 error_handling.py:70] Error recorded from training_loop: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./albert_large_zh/bert_model.ckpt
INFO:tensorflow:training_loop marked as finished
I1013 17:11:41.890880 140328154277632 error_handling.py:96] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W1013 17:11:41.891006 140328154277632 error_handling.py:130] Reraising captured error
Traceback (most recent call last):
  File "run_classifier.py", line 947, in <module>
    tf.app.run()
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "run_classifier.py", line 819, in main
    estimator.train(input_fn=train_input_fn, max_steps=num_train_steps)
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2876, in train
    rendezvous.raise_errors()
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 131, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2871, in train
    saving_listeners=saving_listeners)
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 367, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1158, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1188, in _train_model_default
    features, labels, ModeKeys.TRAIN, self.config)
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2709, in _call_model_fn
    config)
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1146, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2967, in _model_fn
    features, labels, is_export_mode=is_export_mode)
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1549, in call_without_tpu
    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1867, in _call_model_fn
    estimator_spec = self._model_fn(features=features, **kwargs)
  File "run_classifier.py", line 498, in model_fn
    ) = modeling.get_assignment_map_from_checkpoint(tvars, init_checkpoint)
  File "/home/lcy/nlp/SecretProject/ALBERT/albert_zh/modeling.py", line 352, in get_assignment_map_from_checkpoint
    init_vars = tf.train.list_variables(init_checkpoint)
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_utils.py", line 97, in list_variables
    reader = load_checkpoint(ckpt_dir_or_file)
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_utils.py", line 66, in load_checkpoint
    return pywrap_tensorflow.NewCheckpointReader(filename)
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 636, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
  File "/home/lcy/.conda/envs/lcyVenv/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 648, in __init__
    this = _pywrap_tensorflow_internal.new_CheckpointReader(filename)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./albert_large_zh/bert_model.ckpt
```

请问该如何解决？非常感谢

**Comment by brightmart** [comment]
你看看这个参数init_checkpoint对应的checkpoint的名称，是否是以bert_model.ckpt开头的，可能叫albert_model.ckpt.

**Comment by thousfeet** [comment]
`./albert_large_zh`这个路径下只有这些文件：
没有.ckpt
```
albert_config                   bert_utils.py               data         nohup.out                   __pycache__  run_classifier.py   tokenization.py
albert_large_lcqmc_checkpoints  create_pretrain_data.sh     lcqmc        optimization_finetuning.py  README.md    run_pretraining.py
albert_large_zh                 create_pretraining_data.py  modeling.py  optimization.py             resources    test_changes.py
```

**Comment by brightmart** [comment]
你需要下载预训练的文件，并解压到相应的目录，然后在指定init_checkpoint使用这个目录里的checkpoint

**Comment by thousfeet** [comment]
我已下载了albert_large_zh并解压到了albert_zh文件夹下，
albert_zh文件夹目录是这样
```
(base) lcy@bpm201:~/Project/ALBERT/albert_zh$ ls
albert_config                   bert_utils.py               data         nohup.out                   __pycache__  run_classifier.py   tokenization.py
albert_large_lcqmc_checkpoints  create_pretrain_data.sh     lcqmc        optimization_finetuning.py  README.md    run_pretraining.py
albert_large_zh                 create_pretraining_data.py  modeling.py  optimization.py             resources    test_changes.py
```
albert_large_zh文件夹：
```
(base) lcy@bpm201:~/Project/ALBERT/albert_zh/albert_large_zh$ ls
albert_config_large.json  albert_model.ckpt.data-00000-of-00001  albert_model.ckpt.index  albert_model.ckpt.meta  checkpoint  vocab.txt
```
按照ERROR提示缺失的文件是`./albert_large_zh/bert_model.ckpt`，查看了下确实没有
```
(base) lcy@bpm201:~/Project/ALBERT/albert_zh$ cat ./albert_large_zh/bert_model.ckpt
cat: ./albert_large_zh/bert_model.ckpt: No such file or directory
```

请问是我哪里弄错了吗？非常感谢

**Comment by EndlessLethe** [comment]
这里的model名称是albert_model
```
--init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt
```
应该是
```
--init_checkpoint=$BERT_BASE_DIR/albert_model.ckpt
```

**Comment by thousfeet** [comment]
明白了 谢谢
