### ISSUE TITLE
请问如何加载已经训练好的模型，在自己的数据上继续训练

### ISSUE THREAD

**Issue by woyijkl1** [brightmart/albert_zh#55]
如题

**Comment by woyijkl1** [comment]
运行 
export BERT_BASE_DIR=/data/yinrongdi/bert/albert
python run_pretraining.py --input_file=./data/tf*.tfrecord  \
--output_dir=./check_output/ --do_train=True --do_eval=True --bert_config_file=$BERT_BASE_DIR/albert_config_large.json \
--train_batch_size=64 --max_seq_length=512 --max_predictions_per_seq=76 \
--num_train_steps=125000 --num_warmup_steps=12500 --learning_rate=0.00176    \
--save_checkpoints_steps=2000   --init_checkpoint=$BERT_BASE_DIR/albert_model.ckpt
报错
报错信息如下：
E1102 15:59:09.764442 140393369360192 error_handling.py:70] Error recorded from training_loop: Key: masked_lm_ids.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[IteratorGetNext]]
I1102 15:59:09.764675 140393369360192 error_handling.py:96] training_loop marked as finished
W1102 15:59:09.764772 140393369360192 error_handling.py:130] Reraising captured error
Traceback (most recent call last):
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Key: masked_lm_ids.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[IteratorGetNext]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_pretraining.py", line 501, in <module>
    tf.app.run()
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "run_pretraining.py", line 475, in main
    estimator.train(input_fn=train_input_fn, max_steps=FLAGS.num_train_steps)
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2876, in train
    rendezvous.raise_errors()
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 131, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2871, in train
    saving_listeners=saving_listeners)
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 367, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1158, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1192, in _train_model_default
    saving_listeners)
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1484, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1252, in run
    run_metadata=run_metadata)
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1353, in run
    raise six.reraise(*original_exc_info)
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1338, in run
    return self._sess.run(*args, **kwargs)
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1411, in run
    run_metadata=run_metadata)
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1169, in run
    return self._sess.run(*args, **kwargs)
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/yinrongdi/anaconda3/envs/py3_4.0/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Key: masked_lm_ids.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[IteratorGetNext]]

**Comment by brightmart** [comment]
预训练的时候，生成数据和预训练的序列长度和mask的比例必须一直

**Comment by 1810325** [comment]
@brightmart 请问这个模型了一用来做mnist类似的字符识别吗

**Comment by brightmart** [comment]
那个是图像的模型，这个是文本的模型，不同的吧
